--- #YAML:1.0
name:               Lexical-Hints
version:            0.000002
abstract:           A featureful replacement for create_distdirH
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            artistic2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:        5.01
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
